#!/bin/bash
#pin，dir绝对路径
#变量定义等号两边不能有空格
#变量使用可以{}，不能Makefile的()
############################################
PIN="/home/e/pin/pin"
LOG="/home/e/getProcessFuncCallRelation/Log/axiba.log"
MY_SO="/home/e/getProcessFuncCallRelation/Obj/Main.so"
PROCESS_DIR="/home/e/getProcessFuncCallRelation/Test"
PROCESS=${PROCESS_DIR}"/test.o"
PROCESS_="/usr/bin/firefox"

make

cd $PROCESS_DIR
make

$PIN -t $MY_SO -- $PROCESS_

indent -linux $LOG
